### ISSUE TITLE
date range over-rides inurl:

### ISSUE THREAD

**Issue by johngh** [amasad/eHistory#10]
If you want to find all the items from a given URL between two dates and use the advanced interface, it gives you a query of:

startTime:02/01/2013 endTime:03/01/2013 inurl:http://url.i.want.to.find/

Unfortunately this query ignores the URL and just returns all items between the two dates.

I found if I constructed my query manually (i.e. NOT in advanced mode) and used this search string:

startTime:02/01/2013 endTime:03/01/2013 AND http://url.i.want.to.find/

(AND is literally the word "AND")

it gave me what I needed - that is all the items containing that URL between those dates... unfortunately it also includes pages which contain that URL as part of the content.

Ideally you should be able to specify BOTH inurl: AND a date range

**Comment by amasad** [comment]
This is working fine for me:

```
startTime:05/01/2013 endTime:06/03/2013 inurl:google.com
```

In both modes.

Is there a specific URL that this happens on?

**Comment by amasad** [comment]
[Cleaning up here] This looks like it's working fine. If the problem persists please reopen.
