### ISSUE TITLE
Timestamp off by 12 hours

### ISSUE THREAD

**Issue by ghost** [amasad/eHistory#12]
The time on my computer is correct; 9:34 PM but when I open eHistory it lists 9:34 AM.    What is the fix?

**Comment by amasad** [comment]
I can't reproduce this issue. 
- What part of the world are you? I'll try to set my clock to your timezone and see if that changes things.
- and have you changed timezones recently?

**Comment by ghost** [comment]
California. No, I haven't changed time zones recently.

**Comment by itw02** [comment]
I am having the exact same problem.. 12 hrs off. 
I'm using eastern standard time in the US.
Any fixes?

**Comment by itw02** [comment]
On up to date Chrome (Version 29.0.1547.65)

**Comment by amasad** [comment]
OK, fix is live, can you guys confirm this fixes it for you?

**Comment by amasad** [comment]
If is this still wrong please reopen
