### ISSUE TITLE
Older version

### ISSUE THREAD

**Issue by Demonkunga** [amasad/eHistory#2]
In an older version you allowed searching for parts of words in your advanced search area. Why doesn't that work anymore?

**Comment by amasad** [comment]
You still can, as an example:

1- Search Google for "aabbccddee"
2- Goto eHistory and type "aabbcc" in the "Text" textbox

You would get back the "aabbccddee" google search page.

You could also try typing "aabbcc" in the "Title" or "URL" textboxes and get the same result back.

The only feature I rolled back was the REGEXP search.

Are you referring to the REGEXP feature, or am I misunderstanding the issue?

**Comment by Demonkunga** [comment]
I was referring to searching, for example, "bbcc"

**Comment by amasad** [comment]
You are right, but I doubt that feature existed in previous versions..
I'll look into it and if doesn't cause any drop in search speed I will add it.

Thanks.

**Comment by Demonkunga** [comment]
I don't understand why Google doesn't allow it in the first place. They do for bookmarks.

**Comment by max99x** [comment]
Most likely because typically there are a few orders of magnitude more history items than there are bookmarks.

**Comment by Demonkunga** [comment]
I figured as much. Very true. They are in the process of adding partial searching to the address bar, though. I was tracking it at one point, I'm not sure how far along it is at the moment though.

**Comment by amasad** [comment]
[cleaning up]
