### ISSUE TITLE
Problem with Back Button

### ISSUE THREAD

**Issue by taffy2** [amasad/eHistory#3]
I have used 'clear browsing data' from the tools  menu, in Google Chrome, which works but the back button is still highlighted and when I click it I go back a page or if I hold it down it shows my history but not 'full history'.  I installed  eHistory as I thought this would do the trick but the same thing happens.  The only way I can completely clear this is by closing and reopening Chrome.  Can you help?

**Comment by amasad** [comment]
A tab's history would persist even if you cleared your browser history. You should close the tab and its history would be instantly purged.
If your looking for a way to clear a tab's history while its open, I don't think that is possible, anyhow this is not part of eHistory's scope.
You should post your question to http://www.google.com/support/forum/p/Chrome?hl=en

**Comment by taffy2** [comment]
Hi, thank you for your reply. As you say when I close the tab its 
history is purged. I didn't realise I couldn't clear a tab's history 
while it is open with Google Chrome because I can with Firefox.  I have 
now posted my question on the Chrome forum.  Thank you once again and 
eHistory is great for other things.
