### ISSUE TITLE
Shift-click mass selection no longer available

### ISSUE THREAD

**Issue by ghost** [amasad/eHistory#9]
With Chrome's History function, one can select a range of pages, sites or URLs by clicking one item, the first item of a selected range, and shift-clicking another item, the last item of a selected range. All items in between the initial click and the following shift-click are selected, too, and available to be deleted with one click of the Remove selected items button. This click/shift-click selected range feature is no longer available with eHistory enabled.

**Comment by amasad** [comment]
I implemented this feature and it's live. Thanks for reporting this
